# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: .packit/polkit.spec

# add or remove files that should be synced
files_to_sync:
    - .packit/polkit.spec
    - .packit/polkit.sysusers
    - packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: polkit
# downstream (Fedora) RPM package name
downstream_package_name: polkit

jobs:
- job: copr_build
  trigger: pull_request
  targets:
  - fedora-all-aarch64
  - fedora-all-ppc64le
  - fedora-all-s390x
  - fedora-all-x86_64

- job: tests
  trigger: pull_request
  fmf_path: test/integration/
  tmt_plan: upstream-ci
  targets:
  - fedora-all-aarch64
  - fedora-all-x86_64
